In [2]:
import pandas as pd

In [6]:
career_info = pd.read_csv("Player_Career_Info.csv")
career_info.head()

,player,player_id,pos,ht_in_in,wt,birth_date,colleges,from,to,debut,hof
0,Hank Biasatti,biasaha01,G,71.0,175.0,1922-01-14,Assumption University,1947,1947,1946-11-01T00:00:00Z,False
1,Tommy Byrnes,byrneto01,F-G,75.0,175.0,1923-02-19,Seton Hall,1947,1951,1946-11-01T00:00:00Z,False
2,Bob Fitzgerald,fitzgbo01,F-C,77.0,190.0,1923-03-14,Seton Hall,1947,1949,1946-11-01T00:00:00Z,False
3,Dick Fitzgerald,fitzgdi01,F,74.0,175.0,1920-11-18,Fordham,1947,1948,1946-11-01T00:00:00Z,False
4,Frank Fucarino,fucarfr01,F,74.0,175.0,1920-07-24,Long Island University,1947,1947,1946-11-01T00:00:00Z,False

In [9]:
#calculate players career length
career_info_length = career_info[["player_id", "player", "pos", "ht_in_in", "wt", "from", "to", "hof"]].copy()
career_info_length["career_length"] = career_info_length["to"] - career_info_length["from"] + 1

career_info_length.head()

,player_id,player,pos,ht_in_in,wt,from,to,hof,career_length
0,biasaha01,Hank Biasatti,G,71.0,175.0,1947,1947,False,1
1,byrneto01,Tommy Byrnes,F-G,75.0,175.0,1947,1951,False,5
2,fitzgbo01,Bob Fitzgerald,F-C,77.0,190.0,1947,1949,False,3
3,fitzgdi01,Dick Fitzgerald,F,74.0,175.0,1947,1948,False,2
4,fucarfr01,Frank Fucarino,F,74.0,175.0,1947,1947,False,1

In [10]:
totals = pd.read_csv("Player_Totals.csv")
totals.head()

,season,lg,player,player_id,age,team,pos,g,gs,mp,...,orb,drb,trb,ast,stl,blk,tov,pf,pts,trp_dbl
0,2026,NBA,Precious Achiuwa,achiupr01,26.0,SAC,C,73,57.0,1745.0,...,177.0,315.0,492.0,101,65.0,50.0,65.0,123.0,736,0.0
1,2026,NBA,Steven Adams,adamsst01,32.0,HOU,C,32,11.0,730.0,...,145.0,131.0,276.0,48,22.0,20.0,35.0,55.0,187,0.0
2,2026,NBA,Bam Adebayo,adebaba01,28.0,MIA,C,73,73.0,2365.0,...,149.0,583.0,732.0,232,86.0,49.0,120.0,122.0,1468,0.0
3,2026,NBA,Ochai Agbaji,agbajoc01,25.0,2TM,SG,62,13.0,973.0,...,46.0,95.0,141.0,47,24.0,17.0,31.0,93.0,314,0.0
4,2026,NBA,Ochai Agbaji,agbajoc01,25.0,TOR,SG,42,13.0,650.0,...,33.0,62.0,95.0,30,17.0,11.0,19.0,75.0,181,0.0

In [13]:
stats_cols = ["g", "gs", "mp", "fg", "fga", "x3p", "x3pa", "x2p", "x2pa",
            "ft", "fta", "orb", "drb", "trb", "ast", "stl", "blk", "tov",
            "pf", "pts", "trp_dbl"]

# sum columns to find career totals then change the column name to align
totals_career = totals.groupby("player_id")[stats_cols].sum().add_prefix("career_").reset_index()

# rename player_id column because we just changed all columns to start with career_
totals_career = totals_career.rename(columns={"career_player_id": "player_id"})

totals_career.head()

,player_id,career_g,career_gs,career_mp,career_fg,career_fga,career_x3p,career_x3pa,career_x2p,career_x2pa,...,career_orb,career_drb,career_trb,career_ast,career_stl,career_blk,career_tov,career_pf,career_pts,career_trp_dbl
0,abdelal01,385,105.0,5017.0,983,1940,0.0,6.0,983.0,1934.0,...,446.0,851.0,1297.0,125,111.0,107.0,389.0,777.0,2299,0.0
1,abdulka01,1560,789.0,57446.0,15837,28307,1.0,18.0,6692.0,11689.0,...,2975.0,9394.0,17440.0,5660,1160.0,3189.0,2527.0,4657.0,38387,21.0
2,abdulma01,779,0.0,19965.0,3704,8418,0.0,0.0,0.0,0.0,...,18.0,39.0,2234.0,3684,26.0,6.0,0.0,2137.0,9348,1.0
3,abdulma02,586,336.0,15628.0,3514,7943,474.0,1339.0,3040.0,6604.0,...,219.0,868.0,1087.0,2079,487.0,46.0,963.0,1106.0,8553,0.0
4,abdulta01,321,213.0,6826.0,1049,2519,22.0,101.0,1027.0,2418.0,...,428.0,723.0,1151.0,388,263.0,121.0,442.0,688.0,2662,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5411,zizican01,113,27.0,1517.0,273,470,0.0,0.0,273.0,470.0,...,150.0,296.0,446.0,64,22.0,40.0,82.0,170.0,674,0.0
5412,zoetji01,7,0.0,30.0,1,5,0.0,0.0,1.0,5.0,...,3.0,5.0,8.0,1,1.0,3.0,4.0,9.0,2,0.0
5413,zopfbi01,53,0.0,398.0,49,135,0.0,0.0,0.0,0.0,...,0.0,0.0,46.0,73,0.0,0.0,0.0,34.0,118,0.0
5414,zubaciv01,739,582.0,17366.0,3245,5331,1.0,12.0,3244.0,5319.0,...,1975.0,4147.0,6122.0,1067,268.0,706.0,947.0,1736.0,7832,1.0
5415,zunicma01,56,0.0,0.0,98,323,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,50,0.0,0.0,0.0,182.0,273,0.0

In [14]:
totals_career["career_fg_pct"] = totals_career["career_fg"] / totals_career["career_fga"]
totals_career["career_x3p_pct"] = totals_career["career_x3p"] / totals_career["career_x3pa"]
totals_career["career_ft_pct"] = totals_career["career_ft"] / totals_career["career_fta"]
totals_career["career_pts_per_g"] = totals_career["career_pts"] / totals_career["career_g"]
totals_career["career_ast_per_g"] = totals_career["career_ast"] / totals_career["career_g"]
totals_career["career_trb_per_g"] = totals_career["career_trb"] / totals_career["career_g"]

totals_career.head()

,player_id,career_g,career_gs,career_mp,career_fg,career_fga,career_x3p,career_x3pa,career_x2p,career_x2pa,...,career_tov,career_pf,career_pts,career_trp_dbl,career_fg_pct,career_x3p_pct,career_ft_pct,career_pts_per_g,career_ast_per_g,career_trb_per_g
0,abdelal01,385,105.0,5017.0,983,1940,0.0,6.0,983.0,1934.0,...,389.0,777.0,2299,0.0,0.506701,0.000000,0.705508,5.971429,0.324675,3.368831
1,abdulka01,1560,789.0,57446.0,15837,28307,1.0,18.0,6692.0,11689.0,...,2527.0,4657.0,38387,21.0,0.559473,0.055556,0.721410,24.607051,3.628205,11.179487
2,abdulma01,779,0.0,19965.0,3704,8418,0.0,0.0,0.0,0.0,...,0.0,2137.0,9348,1.0,0.440010,NaN,0.758109,12.000000,4.729140,2.867779
3,abdulma02,586,336.0,15628.0,3514,7943,474.0,1339.0,3040.0,6604.0,...,963.0,1106.0,8553,0.0,0.442402,0.353996,0.905254,14.595563,3.547782,1.854949
4,abdulta01,321,213.0,6826.0,1049,2519,22.0,101.0,1027.0,2418.0,...,442.0,688.0,2662,0.0,0.416435,0.217822,0.717881,8.292835,1.208723,3.585670

In [16]:
advanced = pd.read_csv("Advanced.csv")
advanced.head()

,season,lg,player,player_id,age,team,pos,g,gs,mp,...,tov_percent,usg_percent,ows,dws,ws,ws_48,obpm,dbpm,bpm,vorp
0,2026,NBA,Precious Achiuwa,achiupr01,26.0,SAC,C,73,57.0,1745.0,...,9.0,17.6,1.8,1.2,2.9,0.081,-0.5,-1.1,-1.6,0.2
1,2026,NBA,Steven Adams,adamsst01,32.0,HOU,C,32,11.0,730.0,...,16.7,12.1,1.1,1.0,2.1,0.141,-0.1,-0.3,-0.5,0.3
2,2026,NBA,Bam Adebayo,adebaba01,28.0,MIA,C,73,73.0,2365.0,...,8.3,25.0,2.8,3.6,6.4,0.129,1.5,0.4,2.0,2.4
3,2026,NBA,Ochai Agbaji,agbajoc01,25.0,2TM,SG,62,13.0,973.0,...,9.4,14.6,0.1,0.8,0.9,0.046,-3.5,-0.5,-4.0,-0.5
4,2026,NBA,Ochai Agbaji,agbajoc01,25.0,TOR,SG,42,13.0,650.0,...,9.4,13.3,0.0,0.7,0.6,0.048,-4.8,0.1,-4.7,-0.5

In [23]:
# advanced_efficiency_cols cant be added together like the advanced_summation_cols can
advanced_summation_cols = ["ows", "dws", "ws", "vorp"]
advanced_efficiency_cols = ["per", "ts_percent", "bpm", "obpm", "dbpm", "usg_percent"]

# career sums for the stats that are cumulative/ the ones we can just add together
advanced_sums = advanced.groupby("player_id")[advanced_summation_cols].sum().add_prefix("career_").reset_index()
advanced_sums = advanced_sums.rename(columns={"career_player_id": "player_id"})

# multiply the rate/efficiency percentage columns by minutes
advanced_w = advanced.dropna(subset=["mp"]).copy()
weighted_stats = advanced_w[advanced_efficiency_cols].mul(advanced_w["mp"], axis=0)

# add player_id and minutes played back to the dataset and then find the sum
weighted_stats[["player_id", "mp"]] = advanced_w[["player_id", "mp"]]
grouped = weighted_stats.groupby("player_id").sum()

# divide the sum of the weighted stats that we calculated by the total minutes
advanced_weighted = (grouped[advanced_efficiency_cols].div(grouped["mp"], axis=0).add_prefix("career_avg_").reset_index())

# identify players' best season through win share/player impact
peak = advanced.groupby("player_id")["ws"].max().reset_index().rename(columns={"ws": "peak_season_ws"})

advanced_sums.head()

   player_id  career_ows  career_dws  career_ws  career_vorp
0  abdelal01         1.0         6.2        7.1         -2.4
1  abdulka01       179.0        94.5      273.3         85.9
2  abdulma01        18.4        12.9       31.2          0.0
3  abdulma02        16.9         8.4       25.1          4.6
4  abdulta01        -0.6         6.2        5.5         -1.1

In [30]:
# only need number of seasons because we can join the data later to then compare with other columns
# lots of repetitive columns in this set since if a player played 10 seasons they have 10 rows and we already have career stats
season_info = pd.read_csv("Player_Season_Info.csv")
seasons_played = season_info.groupby("player_id")["season"].nunique().reset_index()
seasons_played = seasons_played.rename(columns={"season": "n_seasons"})

seasons_played.head()

   player_id  n_seasons
0  abdelal01          5
1  abdulka01         20
2  abdulma01         10
3  abdulma02          9
4  abdulta01          6

In [46]:
# checking all star status and counting number of times
all_star = pd.read_csv("All-Star_Selections.csv")
all_star_count = all_star.groupby("player_id").size().reset_index(name="n_all_star")

end_of_season = pd.read_csv("End_of_Season_Teams.csv")

# sum awards
all_nba = end_of_season[end_of_season["type"] == "All-NBA"].groupby("player_id").size().reset_index(name="n_all_nba")
all_def = end_of_season[end_of_season["type"] == "All-Defense"].groupby("player_id").size().reset_index(name="n_all_defense")
all_rookie = end_of_season[end_of_season["type"] == "All-Rookie"].groupby("player_id").size().reset_index(name="n_all_rookie")

# finds All-NBA AND 1st team 
first_team_all_nba = end_of_season[(end_of_season["type"] == "All-NBA") & (end_of_season["number_tm"] == "1st")]
first_team_count = first_team_all_nba.groupby("player_id").size().reset_index(name="n_first_team_all_nba")

# sum awards and award share
awards = pd.read_csv("Player_Award_Shares.csv")
award_sum = awards.groupby("player_id").agg(max_award_share=("share", "max"), total_award_share=("share", "sum"), n_award_wins=("winner", "sum"),).reset_index()

# keep all awards with MVP in the name, not case sensitive
# ~awards flips the entire column of true/false values similar to NOT but for an entire column of values
mvp = awards[awards["award"].str.contains("mvp", case = False, na = False) & ~awards["award"].str.contains("clutch|def|roy|6th|sixth", case=False, na=False)]

mvp_sum = mvp.groupby("player_id").agg(mvp_max_share=("share", "max"),n_mvp_wins=("winner", "sum"),).reset_index()

all_star_count.head()

   player_id  n_all_star
0  abdulka01          19
1  abdulma01           1
2  abdursh01           1
3  adamsal01           1
4  adamsmi01           1

In [50]:
# Now, we can finally combine all the data into one dataset

NBA_data = base.merge(totals_career, on="player_id", how="left")
NBA_data = NBA_data.merge(advanced_sums, on="player_id", how="left")
NBA_data = NBA_data.merge(advanced_weighted, on="player_id", how="left")
NBA_data = NBA_data.merge(peak, on="player_id", how="left")
NBA_data = NBA_data.merge(seasons_played, on="player_id", how="left")
NBA_data = NBA_data.merge(all_star_count, on="player_id", how="left")
NBA_data = NBA_data.merge(all_nba, on="player_id", how="left")
NBA_data = NBA_data.merge(all_def, on="player_id", how="left")
NBA_data = NBA_data.merge(all_rookie, on="player_id", how="left")
NBA_data = NBA_data.merge(first_team_count, on="player_id", how="left")
NBA_data = NBA_data.merge(award_sum, on="player_id", how="left")
NBA_data = NBA_data.merge(mvp_sum, on="player_id", how="left")

NBA_data.head()

,player_id,player,pos,ht_in_in,wt,from,to,hof,career_len_listed,career_g,...,n_all_star,n_all_nba,n_all_defense,n_all_rookie,n_first_team_all_nba,max_award_share,total_award_share,n_award_wins,mvp_max_share,n_mvp_wins
0,biasaha01,Hank Biasatti,G,71.0,175.0,1947,1947,False,1,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,byrneto01,Tommy Byrnes,F-G,75.0,175.0,1947,1951,False,5,368,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,fitzgbo01,Bob Fitzgerald,F-C,77.0,190.0,1947,1949,False,3,138,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,fitzgdi01,Dick Fitzgerald,F,74.0,175.0,1947,1948,False,2,61,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,fucarfr01,Frank Fucarino,F,74.0,175.0,1947,1947,False,1,28,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [51]:
# for players that didnt win an award or appear in All-Star selection, we want to just put in 0 for the missing value
missing_cols = ["n_all_star", "n_all_nba", "n_all_defense", "n_all_rookie", "n_first_team_all_nba", "n_award_wins", "n_mvp_wins", "max_award_share", "total_award_share", "mvp_max_share"]
NBA_data[missing_cols] = NBA_data[missing_cols].fillna(0)

# drop any player with no career stats
NBA_data = NBA_data.dropna(subset = ["career_g"])

NBA_data.shape

(5416, 58)