In [1]:
import pandas as pd
import numpy as np

In [2]:
import os
from pathlib import Path
# Force working directory to the notebook's own folder
NOTEBOOK_DIR = Path().resolve()
os.chdir(NOTEBOOK_DIR)
DATA_DIR = NOTEBOOK_DIR / "data"

In [3]:
# datasets we think are relevant to this problem
# problem: predict whether or not they are in hall of fame
advanced = pd.read_csv(DATA_DIR / "Advanced.csv")
player_career = pd.read_csv(DATA_DIR / "Player Career Info.csv")
player_total = pd.read_csv(DATA_DIR / "Player Totals.csv")
player_award = pd.read_csv(DATA_DIR / "Player Award Shares.csv")
player_season = pd.read_csv(DATA_DIR / "Player Season Info.csv")
all_star = pd.read_csv(DATA_DIR / "All-Star Selections.csv")
end_of_season = pd.read_csv(DATA_DIR / "End of Season Teams.csv")
# hall_of_fame = player_career[player_career["hof"] == True]

In [4]:
advanced

,season,lg,player,player_id,age,team,pos,g,gs,mp,...,tov_percent,usg_percent,ows,dws,ws,ws_48,obpm,dbpm,bpm,vorp
0,2026,NBA,Precious Achiuwa,achiupr01,26.0,SAC,C,73,57.0,1745.0,...,9.0,17.6,1.8,1.2,2.9,0.081,-0.5,-1.1,-1.6,0.2
1,2026,NBA,Steven Adams,adamsst01,32.0,HOU,C,32,11.0,730.0,...,16.7,12.1,1.1,1.0,2.1,0.141,-0.1,-0.3,-0.5,0.3
2,2026,NBA,Bam Adebayo,adebaba01,28.0,MIA,C,73,73.0,2365.0,...,8.3,25.0,2.8,3.6,6.4,0.129,1.5,0.4,2.0,2.4
3,2026,NBA,Ochai Agbaji,agbajoc01,25.0,2TM,SG,62,13.0,973.0,...,9.4,14.6,0.1,0.8,0.9,0.046,-3.5,-0.5,-4.0,-0.5
4,2026,NBA,Ochai Agbaji,agbajoc01,25.0,TOR,SG,42,13.0,650.0,...,9.4,13.3,0.0,0.7,0.6,0.048,-4.8,0.1,-4.7,-0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33334,1947,BAA,Ray Wertis,wertira01,23.0,2TM,NaN,61,NaN,NaN,...,NaN,NaN,-1.2,0.6,-0.6,NaN,NaN,NaN,NaN,NaN
33335,1947,BAA,Ray Wertis,wertira01,23.0,TRH,NaN,18,NaN,NaN,...,NaN,NaN,-0.6,0.3,-0.3,NaN,NaN,NaN,NaN,NaN
33336,1947,BAA,Ray Wertis,wertira01,23.0,CLR,NaN,43,NaN,NaN,...,NaN,NaN,-0.6,0.3,-0.4,NaN,NaN,NaN,NaN,NaN
33337,1947,BAA,Max Zaslofsky,zasloma01,21.0,CHS,SG,61,NaN,NaN,...,NaN,NaN,7.6,2.0,9.6,NaN,NaN,NaN,NaN,NaN
33338,1947,BAA,Harry Zeller,zelleha01,27.0,PIT,NaN,48,NaN,NaN,...,NaN,NaN,4.2,-0.5,3.7,NaN,NaN,NaN,NaN,NaN

In [5]:
player_career

,player,player_id,pos,ht_in_in,wt,birth_date,colleges,from,to,debut,hof
0,Hank Biasatti,biasaha01,G,71.0,175.0,1922-01-14,Assumption University,1947,1947,1946-11-01T00:00:00Z,False
1,Tommy Byrnes,byrneto01,F-G,75.0,175.0,1923-02-19,Seton Hall,1947,1951,1946-11-01T00:00:00Z,False
2,Bob Fitzgerald,fitzgbo01,F-C,77.0,190.0,1923-03-14,Seton Hall,1947,1949,1946-11-01T00:00:00Z,False
3,Dick Fitzgerald,fitzgdi01,F,74.0,175.0,1920-11-18,Fordham,1947,1948,1946-11-01T00:00:00Z,False
4,Frank Fucarino,fucarfr01,F,74.0,175.0,1920-07-24,Long Island University,1947,1947,1946-11-01T00:00:00Z,False
...,...,...,...,...,...,...,...,...,...,...,...
5411,Alex Antetokounmpo,antetal01,F,80.0,214.0,2001-08-27,NaN,2026,2026,2026-03-31T00:00:00Z,False
5412,Lucas Williamson,willilu01,G,76.0,205.0,1999-01-28,Loyola Chicago,2026,2026,2026-04-01T00:00:00Z,False
5413,Toby Okani,okanito01,F,80.0,210.0,2001-10-05,"Duquesne, University of Illinois at Chicago, W...",2026,2026,2026-04-03T00:00:00Z,False
5414,Josh Oduro,odurojo01,F,81.0,240.0,2000-10-14,"George Mason, Providence",2026,2026,2026-04-07T00:00:00Z,False
5415,Hayden Gray,grayha01,NaN,NaN,NaN,NaN,NaN,2026,2026,2026-04-12T00:00:00Z,False

In [6]:
player_total

,season,lg,player,player_id,age,team,pos,g,gs,mp,...,orb,drb,trb,ast,stl,blk,tov,pf,pts,trp_dbl
0,2026,NBA,Precious Achiuwa,achiupr01,26.0,SAC,C,73,57.0,1745.0,...,177.0,315.0,492.0,101,65.0,50.0,65.0,123.0,736,0.0
1,2026,NBA,Steven Adams,adamsst01,32.0,HOU,C,32,11.0,730.0,...,145.0,131.0,276.0,48,22.0,20.0,35.0,55.0,187,0.0
2,2026,NBA,Bam Adebayo,adebaba01,28.0,MIA,C,73,73.0,2365.0,...,149.0,583.0,732.0,232,86.0,49.0,120.0,122.0,1468,0.0
3,2026,NBA,Ochai Agbaji,agbajoc01,25.0,2TM,SG,62,13.0,973.0,...,46.0,95.0,141.0,47,24.0,17.0,31.0,93.0,314,0.0
4,2026,NBA,Ochai Agbaji,agbajoc01,25.0,TOR,SG,42,13.0,650.0,...,33.0,62.0,95.0,30,17.0,11.0,19.0,75.0,181,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33334,1947,BAA,Ray Wertis,wertira01,23.0,2TM,NaN,61,NaN,NaN,...,NaN,NaN,NaN,39,NaN,NaN,NaN,82.0,214,0.0
33335,1947,BAA,Ray Wertis,wertira01,23.0,TRH,NaN,18,NaN,NaN,...,NaN,NaN,NaN,18,NaN,NaN,NaN,29.0,99,0.0
33336,1947,BAA,Ray Wertis,wertira01,23.0,CLR,NaN,43,NaN,NaN,...,NaN,NaN,NaN,21,NaN,NaN,NaN,53.0,115,0.0
33337,1947,BAA,Max Zaslofsky,zasloma01,21.0,CHS,SG,61,NaN,NaN,...,NaN,NaN,NaN,40,NaN,NaN,NaN,121.0,877,0.0
33338,1947,BAA,Harry Zeller,zelleha01,27.0,PIT,NaN,48,NaN,NaN,...,NaN,NaN,NaN,31,NaN,NaN,NaN,177.0,362,0.0

In [7]:
player_award

,season,award,player,player_id,age,first,pts_won,pts_max,share,winner
0,2025,nba clutch_poy,Jalen Brunson,brunsja01,28,70.0,426.0,500.0,0.852,True
1,2025,nba clutch_poy,Nikola Jokić,jokicni01,29,26.0,312.0,500.0,0.624,False
2,2025,nba clutch_poy,Anthony Edwards,edwaran01,23,2.0,47.0,500.0,0.094,False
3,2025,nba clutch_poy,Trae Young,youngtr01,26,0.0,44.0,500.0,0.088,False
4,2025,nba clutch_poy,Stephen Curry,curryst01,36,1.0,27.0,500.0,0.054,False
...,...,...,...,...,...,...,...,...,...,...
3460,1952,nba roy,Bill Tosheff,toshebi01,25,NaN,NaN,NaN,NaN,True
3461,1951,nba roy,Paul Arizin,arizipa01,22,NaN,NaN,NaN,NaN,True
3462,1950,nba roy,Alex Groza,grozaal01,23,NaN,NaN,NaN,NaN,True
3463,1949,baa roy,Howie Shannon,shannho01,25,NaN,NaN,NaN,NaN,True
3464,1948,baa roy,Paul Hoffman,hoffmpa01,22,NaN,NaN,NaN,NaN,True

In [8]:
player_season

       season   lg              player  player_id   age team  pos  experience
0        1947  BAA      John Abramovic  abramjo01  27.0  PIT  NaN           1
1        1947  BAA       Chet Aubuchon  aubucch01  30.0  DTF  NaN           1
2        1947  BAA          Norm Baker  bakerno01  23.0  CHS  NaN           1
3        1947  BAA  Herschel Baltimore  baltihe01  25.0  STB  NaN           1
4        1947  BAA           John Barr   barrjo01  28.0  STB  NaN           1
...       ...  ...                 ...        ...   ...  ...  ...         ...
33334    2026  NBA      Omer Yurtseven  yurtsom01  27.0  GSW    C           4
33335    2026  NBA      Rocco Zikarsky  zikarro01  19.0  MIN    C           1
33336    2026  NBA         Ivica Zubac  zubaciv01  28.0  2TM    C          10
33337    2026  NBA         Ivica Zubac  zubaciv01  28.0  IND    C          10
33338    2026  NBA         Ivica Zubac  zubaciv01  28.0  LAC    C          10

[33339 rows x 8 columns]

In [9]:
all_star

               player  player_id        team  season   lg  replaced
0      Scottie Barnes  barnesc01  Team Stars    2026  NBA     False
1        Devin Booker  bookede01  Team Stars    2026  NBA     False
2     Cade Cunningham  cunnica01  Team Stars    2026  NBA     False
3         Jalen Duren  durenja01  Team Stars    2026  NBA     False
4     Anthony Edwards  edwaran01  Team Stars    2026  NBA     False
...               ...        ...         ...     ...  ...       ...
2053       Alex Groza  grozaal01        West    1951  NBA     False
2054     George Mikan  mikange01        West    1951  NBA     False
2055   Vern Mikkelsen  mikkeve01        West    1951  NBA     False
2056      Jim Pollard  pollaji01        West    1951  NBA     False
2057      Fred Schaus  schaufr01        West    1951  NBA     False

[2058 rows x 6 columns]

In [10]:
end_of_season

,season,lg,type,number_tm,player,player_id,position
0,2025,NBA,All-Defense,1st,Dyson Daniels,daniedy01,NaN
1,2025,NBA,All-Defense,1st,Luguentz Dort,dortlu01,NaN
2,2025,NBA,All-Defense,1st,Draymond Green,greendr01,NaN
3,2025,NBA,All-Defense,1st,Evan Mobley,mobleev01,NaN
4,2025,NBA,All-Defense,1st,Amen Thompson,thompam01,NaN
...,...,...,...,...,...,...,...
2217,1947,BAA,All-BAA,2nd,Frankie Baumholtz,baumhfr01,NaN
2218,1947,BAA,All-BAA,2nd,Ernie Calverley,calveer01,NaN
2219,1947,BAA,All-BAA,2nd,Chick Halbert,halbech01,NaN
2220,1947,BAA,All-BAA,2nd,John Logan,loganjo01,NaN
2221,1947,BAA,All-BAA,2nd,Fred Scolari,scolafr01,NaN